import { Pizza } from "./Pizza";

export const database: Pizza[] = [
  new Pizza(1, "She Made Them Do It"),
  new Pizza(2, "Poka stanitsa spit"),
  new Pizza(3, "Memory Lane"),
  new Pizza(4, "No Through Road"),
  new Pizza(5, "Malcolm & Eddie"),
  new Pizza(6, "Violet"),
  new Pizza(7, "Last Call with Carson Daly"),
  new Pizza(8, "The Yellow Badge of Courage"),
  new Pizza(9, "Doctor Who: The Companion Chronicles"),
  new Pizza(10, "The Feed"),
  new Pizza(11, "Emmerdale Farm"),
  new Pizza(12, "The Jeselnik Offensive"),
  new Pizza(13, "Zero Minute"),
  new Pizza(14, "Nina and the Neurons Go Inventing"),
  new Pizza(15, "Dynamo"),
  new Pizza(16, "Ammattimies"),
  new Pizza(17, "Happening Now"),
  new Pizza(18, "The O'Reilly Factor"),
  new Pizza(19, "How Do I Look?"),
  new Pizza(20, "Electric Playground"),
  new Pizza(21, "Commissaire Laviolette"),
  new Pizza(22, "The Young Doctors"),
  new Pizza(23, "Married with Children"),
  new Pizza(24, "Le clan Pasquier"),
  new Pizza(25, "The Gale Storm Show: Oh! Susanna"),
  new Pizza(26, "Serangoon Road"),
  new Pizza(27, "The Young Doctors"),
  new Pizza(28, "Family Matters"),
  new Pizza(29, "Motormouth"),
  new Pizza(30, "Antiques Roadshow"),
  new Pizza(31, "Wasak"),
  new Pizza(32, "Prime News"),
  new Pizza(33, "May bukas pa"),
  new Pizza(34, "The Hollywood Squares"),
  new Pizza(35, "Els matins a TV3"),
  new Pizza(36, "Your Favorite Story"),
  new Pizza(37, "Los desayunos de TVE"),
  new Pizza(38, "The Small House at Allington"),
  new Pizza(39, "Minute to Win It"),
  new Pizza(40, "El ministerio del tiempo"),
  new Pizza(41, "The Fabulous Picture Show"),
  new Pizza(42, "Black Jack"),
  new Pizza(43, "Cutting Edge"),
  new Pizza(44, "Judge Joe Brown"),
  new Pizza(45, "All Saints"),
  new Pizza(46, "Quincy M.E."),
  new Pizza(47, "Neighbours"),
  new Pizza(48, "Chistoserdechnoe priznanie"),
  new Pizza(49, "John Halifax, Gentleman"),
  new Pizza(50, "Paul Flynn"),
  new Pizza(51, "Texas Monthly Talks"),
  new Pizza(52, "David Copperfield"),
  new Pizza(53, "Obruchalnoe koltso"),
  new Pizza(54, "Rock Macabre"),
  new Pizza(55, "The Tonight Show Starring Johnny Carson"),
  new Pizza(56, "Daesh molodezh"),
  new Pizza(57, "Wicked Wicked Games"),
  new Pizza(58, "Music Fair"),
  new Pizza(59, "Flip My Food with Chef Jeff"),
  new Pizza(60, "Un hombre solo"),
  new Pizza(61, "My S Rostova"),
  new Pizza(62, "Zwei bei Kallwass"),
  new Pizza(63, "Last Call with Carson Daly"),
  new Pizza(64, "Jimmy Kimmel Live!"),
  new Pizza(65, "Plebs"),
  new Pizza(66, "Lonelygirl15"),
  new Pizza(67, "Plus belle la vie"),
  new Pizza(68, "Watch What Happens: Live"),
  new Pizza(69, "WRAL Murder Trials"),
  new Pizza(70, "Secrets of the Bible"),
  new Pizza(71, "Six O'Clock News"),
  new Pizza(72, "Jackie Gleason: American Scene Magazine"),
];
